#!/usr/bin/env python
"""Comprehensive end-to-end test suite for PhyloSlicer.

This script runs all test categories defined in TEST_PLAN.md and produces
a detailed pass/fail report. Each test is self-contained and uses the
test data generated by generate_test_data.py.
"""

from __future__ import annotations

import json
import math
import os
import sys
import time
import traceback
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd

# Ensure the package is importable
REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "src"))

import phyloslicer as ps
from phyloslicer.compat import phylo_pieces, squeeze_int, squeeze_root, squeeze_tips
from phyloslicer.compat import prune_tips as compat_prune
from phyloslicer.core.tree import TreeArray
from phyloslicer.indices.api import pb as pb_func
from phyloslicer.indices.api import pb_per_slice, pd_per_slice, pe_per_slice
from phyloslicer.indices.api import pd as pd_func
from phyloslicer.indices.api import pe as pe_func
from phyloslicer.io import (
    align_tree_matrix,
    parse_newick,
    presence_matrix,
    read_nexus,
    write_newick,
)
from phyloslicer.rates.api import cpb_rate, cpd_rate, cpe_rate, rate_profile, sensitivity
from phyloslicer.rates.fitting import fit_rate, origin_time
from phyloslicer.simulate import birth_death_tree, make_dataset, yule_tree
from phyloslicer.slicing.api import (
    prune_tips,
    slice_interval,
    slice_pieces,
    slice_rootward,
    slice_tipward,
)
from phyloslicer.spatial import (
    adjacency_from_bounds,
    adjacency_from_coords,
    from_adjacency_dict,
    rate_map,
    to_adjacency_dict,
)
from phyloslicer.uncertainty import bootstrap_sites, iter_trees, posterior_origin, posterior_rate

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
RESULTS_DIR = Path(__file__).resolve().parent.parent / "results"
LOGS_DIR = Path(__file__).resolve().parent.parent / "logs"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
LOGS_DIR.mkdir(parents=True, exist_ok=True)


@dataclass
class TestResult:
    test_id: str
    category: str
    description: str
    passed: bool
    elapsed_s: float
    error: str = ""
    details: str = ""


results: list[TestResult] = []


def run_test(test_id: str, category: str, desc: str, fn) -> TestResult:
    """Run a single test function and record the result."""
    t0 = time.perf_counter()
    try:
        detail = fn()
        elapsed = time.perf_counter() - t0
        r = TestResult(test_id, category, desc, True, elapsed, "", detail or "")
    except Exception as exc:
        elapsed = time.perf_counter() - t0
        tb = traceback.format_exc()
        r = TestResult(test_id, category, desc, False, elapsed, str(exc), tb)
    results.append(r)
    status = "PASS" if r.passed else "FAIL"
    print(f"  [{status}] {test_id}: {desc}" + (f" ({r.elapsed_s:.3f}s)" if r.passed else ""))
    if not r.passed:
        print(f"         Error: {r.error}")
    return r


# ========================================================================== #
# T-INSTALL: Installation and dependency tests
# ========================================================================== #
def test_install():
    def t01():
        import phyloslicer

        return f"version={phyloslicer.__version__}"

    run_test("T-INSTALL-01", "Install", "import phyloslicer", t01)

    def t02():
        v = ps.__version__
        assert isinstance(v, str) and len(v) > 0
        return f"version={v}"

    run_test("T-INSTALL-02", "Install", "__version__ is a string", t02)

    def t03():
        import numpy
        import scipy

        return f"numpy={numpy.__version__}, scipy={scipy.__version__}"

    run_test("T-INSTALL-03", "Install", "core dependencies importable", t03)

    def t04():
        try:
            import numba

            return f"numba={numba.__version__}"
        except ImportError:
            return "numba not installed (optional, OK)"

    run_test("T-INSTALL-04", "Install", "numba importable", t04)

    def t05():
        try:
            import dendropy

            return f"dendropy={dendropy.__version__}"
        except ImportError:
            return "dendropy not installed (optional, OK)"

    run_test("T-INSTALL-05", "Install", "dendropy importable", t05)

    def t06():
        import subprocess

        # Prefer the installed console script; fall back to module execution so
        # the check also works from a bare source tree.
        cli = os.path.join(os.path.dirname(sys.executable), "phyloslicer")
        if os.path.exists(cli):
            cmd = [cli, "--version"]
            env = dict(os.environ)
        else:
            cmd = [sys.executable, "-m", "phyloslicer", "--version"]
            env = dict(os.environ, PYTHONPATH=str(REPO / "src"))
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=30, env=env)
        assert r.returncode == 0, f"exit code {r.returncode}, stderr={r.stderr}"
        assert "phyloslicer" in r.stdout
        return r.stdout.strip()

    run_test("T-INSTALL-06", "Install", "CLI --version works", t06)


# ========================================================================== #
# T-IO: Input/output tests
# ========================================================================== #
def test_io():
    def t01():
        tree = parse_newick("((A:1,B:1):1,(C:1,D:1):1);")
        assert tree.n_tips == 4
        assert sorted(tree.tip_labels) == ["A", "B", "C", "D"]
        return f"n_tips={tree.n_tips}, labels={tree.tip_labels}"

    run_test("T-IO-01", "IO", "Newick string parsing", t01)

    def t02():
        tree = TreeArray.from_newick(str(DATA_DIR / "medium_tree.tre"))
        assert tree.n_tips == 20
        return f"n_tips={tree.n_tips}, root_age={tree.root_age:.4f}"

    run_test("T-IO-02", "IO", "Newick file reading", t02)

    def t03():
        trees = read_nexus(str(DATA_DIR / "posterior.nex"))
        assert len(trees) == 5
        return f"n_trees={len(trees)}"

    run_test("T-IO-03", "IO", "NEXUS multi-tree reading", t03)

    def t04():
        tree = parse_newick("((A:1[Beta=0.95],B:1):1,(C:1,D:1):1);")
        assert tree.n_tips == 4
        return "comments stripped correctly"

    run_test("T-IO-04", "IO", "Bracket comments stripped", t04)

    def t05():
        tree = parse_newick("(('sp one':1,'sp two':1):1,(C:1,D:1):1);")
        assert "sp one" in tree.tip_labels
        assert "sp two" in tree.tip_labels
        return f"labels={tree.tip_labels}"

    run_test("T-IO-05", "IO", "Quoted labels parsing", t05)

    def t06():
        tree1 = parse_newick("((A:1.5,B:2.5):3.5,(C:1.0,D:4.0):3.0);")
        nw = write_newick(tree1)
        tree2 = parse_newick(nw)
        assert tree1 == tree2, "round-trip mismatch"
        return "round-trip OK"

    run_test("T-IO-06", "IO", "Newick round-trip", t06)

    def t07():
        df = pd.DataFrame(
            {
                "site": ["s1", "s1", "s2", "s2"],
                "species": ["A", "B", "A", "C"],
            }
        )
        mat = presence_matrix(df, site_col="site", species_col="species")
        assert mat.shape == (2, 3)
        assert mat.loc["s1", "A"] == 1.0
        assert mat.loc["s2", "C"] == 1.0
        return f"shape={mat.shape}"

    run_test("T-IO-07", "IO", "Long-to-wide matrix conversion", t07)

    def t08():
        df = pd.DataFrame({"A": [1, 0], "B": [1, 1], "C": [0, 1]}, index=["s1", "s2"])
        mat = presence_matrix(df)
        assert mat.shape == (2, 3)
        return f"shape={mat.shape}"

    run_test("T-IO-08", "IO", "Wide table validation", t08)

    def t09():
        tree = TreeArray.from_newick("((A:1,B:1):1,(C:1,D:1):1);")
        mat = pd.DataFrame(
            {"A": [1, 0], "B": [1, 1], "C": [0, 1], "D": [1, 0], "E": [0, 1]}, index=["s1", "s2"]
        )
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            t2, m2 = align_tree_matrix(tree, mat)
        assert "E" not in m2.columns
        assert set(m2.columns) == {"A", "B", "C", "D"}
        return f"aligned: {t2.n_tips} tips, {m2.shape[1]} species"

    run_test("T-IO-09", "IO", "align_tree_matrix", t09)

    def t10():
        tree = TreeArray.from_newick("((A:1,B:1):1,(C:1,D:1):1);")
        mat = pd.DataFrame({"X": [1, 0], "Y": [1, 1]}, index=["s1", "s2"])
        try:
            align_tree_matrix(tree, mat)
            return "ERROR: should have raised"
        except ValueError:
            return "correctly raised ValueError"

    run_test("T-IO-10", "IO", "No shared species raises ValueError", t10)


# ========================================================================== #
# T-CORE: Core algorithm tests
# ========================================================================== #
def test_core():
    def t01():
        tree = TreeArray.from_newick("((A:1,B:1):1,(C:1,D:1):1);")
        assert tree.n_tips == 4
        assert tree.n_edges == 6
        assert tree.root_age == 2.0
        return f"tips={tree.n_tips}, edges={tree.n_edges}, root_age={tree.root_age}"

    run_test("T-CORE-01", "Core", "TreeArray construction", t01)

    def t02():
        tree = TreeArray.from_newick("((((A:1,B:1):1,C:2):1,D:3):1,E:4);")
        depths = tree.node_depths()
        assert depths[tree.root] == 0.0
        # E is at depth 4, A and B at depth 4
        assert abs(depths[0] - 4.0) < 1e-10  # A
        assert abs(depths[4] - 4.0) < 1e-10  # E
        return "depths correct"

    run_test("T-CORE-02", "Core", "Node depth computation", t02)

    def t03():
        tree = TreeArray.from_newick("((A:1,B:1):1,(C:1,D:1):1);")
        intervals = tree.tip_intervals()
        assert intervals.shape == (6, 2)
        return f"intervals shape={intervals.shape}"

    run_test("T-CORE-03", "Core", "tip_intervals correctness", t03)

    def t04():
        tree = TreeArray.from_newick("((A:1,B:1):1,(C:1,D:1):1);")
        stack = slice_pieces(tree, n=4)
        C = stack.contribution_matrix()
        # Each column should sum to the PD in that slice
        col_sums = C.sum(axis=0)
        assert len(col_sums) == 4
        return f"contribution matrix shape={C.shape}"

    run_test("T-CORE-04", "Core", "Contribution matrix", t04)

    def t05():
        tree = TreeArray.from_newick("((A:1,B:1):1,(C:1,D:1):1);")
        stack = slice_pieces(tree, n=4)
        widths = stack.widths
        assert np.allclose(widths, widths[0]), "equal-time slices should have equal width"
        return f"widths={widths}"

    run_test("T-CORE-05", "Core", "Equal-time slice windows", t05)

    def t06():
        tree = TreeArray.from_newick("((A:1,B:1):1,(C:1,D:1):1);")
        stack = slice_pieces(tree, n=4, criterion="pd")
        contribs = stack.contribution_matrix().sum(axis=0)
        # Each slice should have equal PD
        assert np.allclose(contribs, contribs[0], atol=1e-10), f"PD not equal: {contribs}"
        return f"per-slice PD={contribs}"

    run_test("T-CORE-06", "Core", "Equal-PD slice windows", t06)

    def t07():
        tree = TreeArray.from_newick("((A:1,B:1):1,(C:1,D:1):1);")
        sub = tree.subarray(["A", "B"])
        assert sub.n_tips == 2
        assert set(sub.tip_labels) == {"A", "B"}
        return f"subtree tips={sub.tip_labels}"

    run_test("T-CORE-07", "Core", "subarray pruning", t07)

    def t08():
        tree = TreeArray.from_newick("((A:1,B:1):1,(C:1,D:1):1);")
        assert tree.is_ultrametric
        return "ultrametric=True"

    run_test("T-CORE-08", "Core", "Ultrametric detection", t08)

    def t09():
        tree = TreeArray.from_newick("((A:1,B:2):1,(C:1,D:1):1);")
        assert not tree.is_ultrametric
        return "ultrametric=False"

    run_test("T-CORE-09", "Core", "Non-ultrametric detection", t09)

    def t10():
        tree = TreeArray.from_newick("((A:1,B:1):1,(C:1,D:1):1);")
        assert abs(tree.total_pd() - 6.0) < 1e-10
        return f"total_pd={tree.total_pd()}"

    run_test("T-CORE-10", "Core", "total_pd computation", t10)


# ========================================================================== #
# T-INDICES: Diversity indices tests
# ========================================================================== #
def test_indices():
    tree = TreeArray.from_newick("((A:1,B:1):1,(C:1,D:1):1);")
    mat = pd.DataFrame(
        {"A": [1, 0, 1], "B": [1, 1, 0], "C": [0, 1, 0], "D": [0, 0, 1]}, index=["s1", "s2", "s3"]
    )

    def t01():
        vals = pd_func(tree, mat)
        # s1 has A,B -> edges: (4,5),(5,0),(5,1) -> lengths 1+1+1=3
        assert abs(vals[0] - 3.0) < 1e-10
        return f"pd={vals}"

    run_test("T-INDICES-01", "Indices", "pd() computation", t01)

    def t02():
        vals = pe_func(tree, mat)
        assert len(vals) == 3
        return f"pe={vals}"

    run_test("T-INDICES-02", "Indices", "pe() computation", t02)

    def t03():
        adj = np.array([[1, 1, 0], [1, 1, 1], [0, 1, 1]])
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            res = pb_func(tree, mat, adj)
        assert "PB" in res.columns
        return f"pb shape={res.shape}"

    run_test("T-INDICES-03", "Indices", "pb() full-tree beta", t03)

    def t04():
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            tree2, mat2 = align_tree_matrix(tree, mat)
        stack = slice_pieces(tree2, n=10)
        prof = pd_per_slice(tree2, mat2, stack)
        row_sums = prof.sum(axis=1)
        # row sums should equal total PD per site
        totals = pd_func(tree2, mat2)
        assert np.allclose(row_sums, totals, atol=1e-8)
        return "row_sums match total PD"

    run_test("T-INDICES-04", "Indices", "pd_per_slice row sums = total PD", t04)

    def t05():
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            tree2, mat2 = align_tree_matrix(tree, mat)
        stack = slice_pieces(tree2, n=10)
        prof = pe_per_slice(tree2, mat2, stack)
        assert prof.shape == (3, 10)
        return f"shape={prof.shape}"

    run_test("T-INDICES-05", "Indices", "pe_per_slice shape", t05)

    def t06():
        adj = np.array([[1, 1, 0], [1, 1, 1], [0, 1, 1]])
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            tree2, mat2 = align_tree_matrix(tree, mat)
        stack = slice_pieces(tree2, n=10)
        result = pb_per_slice(tree2, mat2, adj, stack, component="sorensen")
        values = result["values"]
        finite_rows = np.isfinite(values).all(axis=1)
        if finite_rows.any():
            row_sums = values[finite_rows].sum(axis=1)
            assert np.allclose(row_sums, 1.0, atol=1e-8), f"row_sums={row_sums}"
        return "partition property verified"

    run_test("T-INDICES-06", "Indices", "pb_per_slice partition (sum=1)", t06)

    def t07():
        adj = np.array([[1, 1, 0], [1, 1, 1], [0, 1, 1]])
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            tree2, mat2 = align_tree_matrix(tree, mat)
        stack = slice_pieces(tree2, n=10)
        for comp in ["sorensen", "turnover", "nestedness"]:
            result = pb_per_slice(tree2, mat2, adj, stack, component=comp)
            assert result["values"].shape == (3, 10)
        return "all components OK"

    run_test("T-INDICES-07", "Indices", "All beta components", t07)

    def t08():
        adj = np.array([[1, 1, 0], [1, 1, 1], [0, 1, 1]])
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            tree2, mat2 = align_tree_matrix(tree, mat)
        stack = slice_pieces(tree2, n=10)
        for appr in ["multisite", "pairwise"]:
            result = pb_per_slice(tree2, mat2, adj, stack, approach=appr)
            assert result["values"].shape == (3, 10)
        return "both approaches OK"

    run_test("T-INDICES-08", "Indices", "multisite & pairwise approaches", t08)

    def t09():
        adj = np.array([[1, 1, 0], [1, 1, 1], [0, 1, 1]])
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            tree2, mat2 = align_tree_matrix(tree, mat)
        stack = slice_pieces(tree2, n=10)
        r1 = pb_per_slice(tree2, mat2, adj, stack, multisite_domain="mixed")
        r2 = pb_per_slice(tree2, mat2, adj, stack, multisite_domain="paired")
        assert r1["values"].shape == r2["values"].shape
        return "both domains OK"

    run_test("T-INDICES-09", "Indices", "multisite_domain mixed vs paired", t09)

    def t10():
        # Degenerate: all sites identical
        adj = np.array([[1, 1, 0], [1, 1, 1], [0, 1, 1]])
        mat_deg = pd.DataFrame(
            {"A": [1, 1, 1], "B": [1, 1, 1], "C": [0, 0, 0], "D": [0, 0, 0]},
            index=["s1", "s2", "s3"],
        )
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            tree2, mat2 = align_tree_matrix(tree, mat_deg)
        stack = slice_pieces(tree2, n=10)
        result = pb_per_slice(tree2, mat2, adj, stack)
        statuses = result["status"]
        assert "degenerate_neighbourhood" in statuses or "ok" in statuses
        return f"statuses={list(set(statuses))}"

    run_test("T-INDICES-10", "Indices", "Degenerate neighbourhood handling", t10)


# ========================================================================== #
# T-RATES: Cumulative rates tests
# ========================================================================== #
def test_rates():
    tree = yule_tree(30, age=10.0, seed=42)
    mat, _ = make_dataset(n_sites=20, n_species=30, structure="clustered", seed=7)
    mat.columns = tree.tip_labels

    def t01():
        res = cpd_rate(tree, mat, n_slices=50)
        assert "site_id" in res.columns
        assert "CpD" in res.columns
        assert "PD" in res.columns
        assert "pDO" in res.columns
        assert "converged" in res.columns
        assert len(res) == 20
        return f"{len(res)} rows, {sum(res['converged'])} converged"

    run_test("T-RATES-01", "Rates", "cpd_rate DataFrame", t01)

    def t02():
        res = cpe_rate(tree, mat, n_slices=50)
        assert "CpE" in res.columns
        assert "PE" in res.columns
        return f"{len(res)} rows"

    run_test("T-RATES-02", "Rates", "cpe_rate DataFrame", t02)

    def t03():
        adj = adjacency_from_coords(
            mat.index.map(lambda x: float(x)).to_numpy() if False else np.arange(20, dtype=float),
            np.arange(20, dtype=float)[::-1],
            method="knn",
            k=4,
        )
        res = cpb_rate(tree, mat, adj, n_slices=50, component="sorensen")
        assert "CpB" in res.columns
        assert "PB" in res.columns
        return f"{len(res)} rows"

    run_test("T-RATES-03", "Rates", "cpb_rate DataFrame", t03)

    def t04():
        # fit_rate fits cumulative(profile) ~ exp(-r * ages) after
        # normalising cumsum by the total. The model has no intercept,
        # so the recovered rate depends on the shape. We test that the
        # fit converges and produces a positive rate with good R².
        ages = np.array([10.0, 8.0, 6.0, 4.0, 2.0])
        r_true = 0.3
        cum_model = np.exp(-r_true * ages)
        profile = np.diff(np.concatenate([[0.0], cum_model]))
        fit = fit_rate(profile, ages)
        assert fit.converged, f"fit did not converge: {fit.reason}"
        assert fit.rate > 0, f"rate should be positive, got {fit.rate}"
        assert fit.r_squared > 0.7, f"R² too low: {fit.r_squared}"
        # The recovered rate may differ from r_true because of the
        # normalisation (cum[-1] = 1 forces exp(-r*ages[-1]) ≈ 1),
        # but the fit quality should be high.
        return f"rate={fit.rate:.6f}, R²={fit.r_squared:.6f} (converged)"

    run_test("T-RATES-04", "Rates", "fit_rate parameter recovery", t04)

    def t05():
        pXO = origin_time(0.5, percentile=0.95)
        expected = -np.log(1 - 0.95) / 0.5
        assert abs(pXO - expected) < 1e-10
        return f"pXO={pXO:.6f}"

    run_test("T-RATES-05", "Rates", "origin_time computation", t05)

    def t06():
        # Empty site
        mat_empty = mat.copy()
        mat_empty.iloc[0, :] = 0.0
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            res = cpd_rate(tree, mat_empty, n_slices=50)
        assert not res.iloc[0]["converged"]
        assert res.iloc[0]["reason"] != ""
        return (
            f"empty site: converged={res.iloc[0]['converged']}, reason={res.iloc[0]['reason'][:50]}"
        )

    run_test("T-RATES-06", "Rates", "Empty site handling", t06)

    def t07():
        res = cpd_rate(tree, mat, n_slices=50)
        # Check bound flags exist
        assert "at_lower_bound" in res.columns
        assert "at_upper_bound" in res.columns
        return "bound flags present"

    run_test("T-RATES-07", "Rates", "Boundary fit flags", t07)

    def t08():
        sens = sensitivity(tree, mat, slice_grid=[10, 25, 50], rate="cpd", seed=42)
        assert "suggested_slices" in sens.columns
        assert "n_slices" in sens.columns
        return f"sensitivity shape={sens.shape}"

    run_test("T-RATES-08", "Rates", "sensitivity analysis", t08)

    def t09():
        prof = rate_profile(tree, mat, n_slices=50, index="PD", normalize=True)
        assert "values" in prof
        row_sums = prof["values"].sum(axis=1)
        finite = np.isfinite(row_sums)
        assert np.allclose(row_sums[finite], 1.0, atol=1e-8)
        return "normalized profiles sum to 1"

    run_test("T-RATES-09", "Rates", "rate_profile normalized", t09)

    def t10():
        prof = rate_profile(tree, mat, n_slices=50, index="PD", normalize=False)
        row_sums = prof["values"].sum(axis=1)
        totals = pd_func(tree, mat)
        assert np.allclose(row_sums, totals, atol=1e-8)
        return "raw profiles sum to total PD"

    run_test("T-RATES-10", "Rates", "rate_profile raw values", t10)


# ========================================================================== #
# T-SLICING: Slicing tests
# ========================================================================== #
def test_slicing():
    tree = TreeArray.from_newick("((A:1,B:1):1,(C:1,D:1):1);")

    def t01():
        s = slice_rootward(tree, 0.0)
        assert abs(s.pd) < 1e-10
        return f"PD={s.pd}"

    run_test("T-SLICING-01", "Slicing", "slice_rootward(0) = empty", t01)

    def t02():
        s = slice_rootward(tree, 2.0)
        assert abs(s.pd - 6.0) < 1e-10
        return f"PD={s.pd}"

    run_test("T-SLICING-02", "Slicing", "slice_rootward(T) = full tree", t02)

    def t03():
        s = slice_tipward(tree, 0.0)
        assert abs(s.pd - 6.0) < 1e-10
        return f"PD={s.pd}"

    run_test("T-SLICING-03", "Slicing", "slice_tipward(0) = full tree", t03)

    def t04():
        s = slice_tipward(tree, 2.0)
        assert abs(s.pd) < 1e-10
        return f"PD={s.pd}"

    run_test("T-SLICING-04", "Slicing", "slice_tipward(T) = empty", t04)

    def t05():
        s = slice_interval(tree, start=1.5, stop=0.5)
        assert s.pd > 0
        return f"PD={s.pd}"

    run_test("T-SLICING-05", "Slicing", "slice_interval", t05)

    def t06():
        older, younger = slice_interval(tree, 1.5, 0.5, invert=True)
        assert older.pd > 0
        assert younger.pd > 0
        return f"older PD={older.pd}, younger PD={younger.pd}"

    run_test("T-SLICING-06", "Slicing", "slice_interval invert", t06)

    def t07():
        stack = slice_pieces(tree, n=10)
        assert stack.n_slices == 10
        return f"n_slices={stack.n_slices}"

    run_test("T-SLICING-07", "Slicing", "slice_pieces(n=10)", t07)

    def t08():
        stack = slice_pieces(tree, width=0.5)
        assert stack.n_slices >= 1
        return f"n_slices={stack.n_slices}"

    run_test("T-SLICING-08", "Slicing", "slice_pieces(width=0.5)", t08)

    def t09():
        stack = slice_pieces(tree, n=4, criterion="pd")
        contribs = stack.contribution_matrix().sum(axis=0)
        assert np.allclose(contribs, contribs[0], atol=1e-10)
        return f"per-slice PD={contribs}"

    run_test("T-SLICING-09", "Slicing", "slice_pieces criterion=pd", t09)

    def t10():
        kept = prune_tips(tree, 0.5, side="after")
        assert kept.n_tips >= 2
        return f"kept {kept.n_tips} tips"

    run_test("T-SLICING-10", "Slicing", "prune_tips", t10)

    def t11():
        try:
            slice_rootward(tree, 100.0)
            return "ERROR: should raise"
        except ValueError:
            return "correctly raised ValueError"

    run_test("T-SLICING-11", "Slicing", "time > root_age raises", t11)

    def t12():
        try:
            slice_rootward(tree, -1.0)
            return "ERROR: should raise"
        except ValueError:
            return "correctly raised ValueError"

    run_test("T-SLICING-12", "Slicing", "negative time raises", t12)


# ========================================================================== #
# T-UNC: Uncertainty tests
# ========================================================================== #
def test_uncertainty():
    trees = [yule_tree(30, age=10.0, seed=s) for s in range(42, 47)]
    mat, _ = make_dataset(n_sites=15, n_species=30, structure="clustered", seed=7)
    mat.columns = trees[0].tip_labels

    def t01():
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            res = posterior_rate(trees, mat, rate="cpd", n_slices=30, hdi=0.95)
        assert "rate_mean" in res.columns
        assert "hdi_low" in res.columns
        assert "hdi_high" in res.columns
        assert "n_trees" in res.columns
        return f"{len(res)} sites, n_trees={res['n_trees'].iloc[0]}"

    run_test("T-UNC-01", "Uncertainty", "posterior_rate (list input)", t01)

    def t02():
        # Newick string input
        nw = "\n".join(t.to_newick() for t in trees)
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            res = posterior_rate(nw, mat, rate="cpd", n_slices=30)
        assert len(res) == 15
        return f"{len(res)} sites"

    run_test("T-UNC-02", "Uncertainty", "posterior_rate (string input)", t02)

    def t03():
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            res = posterior_origin(trees, mat, rate="cpd", n_slices=30, hdi=0.95)
        assert "origin_median" in res.columns
        return f"{len(res)} sites"

    run_test("T-UNC-03", "Uncertainty", "posterior_origin", t03)

    def t04():
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            boot = bootstrap_sites(trees[0], mat, n_boot=50, rate="cpd", n_slices=30, seed=42)
        assert len(boot) == 50
        return f"{len(boot)} replicates"

    run_test("T-UNC-04", "Uncertainty", "bootstrap_sites", t04)

    def t05():
        # Directory input
        pdir = DATA_DIR / "posterior_trees"
        trees_from_dir = list(iter_trees(str(pdir)))
        assert len(trees_from_dir) == 5
        return f"{len(trees_from_dir)} trees from directory"

    run_test("T-UNC-05", "Uncertainty", "iter_trees (directory)", t05)

    def t06():
        # Bad tree in the list
        good_trees = trees[:4]
        bad_tree = TreeArray.from_newick("((A:1,B:1):1,(C:1,D:1):1);")
        # This tree has different tip labels, so it will fail alignment
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            res = posterior_rate(good_trees + [bad_tree], mat, rate="cpd", n_slices=30)
        # Should still produce results (bad tree skipped)
        assert len(res) == 15
        return f"survived bad tree, n_trees={res['n_trees'].iloc[0]}"

    run_test("T-UNC-06", "Uncertainty", "Bad tree skipped with warning", t06)

    def t07():
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            res = posterior_rate(trees, mat, rate="cpd", n_slices=30, hdi=0.95)
        finite = np.isfinite(res["rate_median"])
        if finite.any():
            for _, row in res[finite].iterrows():
                assert row["hdi_low"] <= row["rate_median"] <= row["hdi_high"], (
                    f"median {row['rate_median']} outside HDI [{row['hdi_low']}, {row['hdi_high']}]"
                )
        return "HDI interval verified"

    run_test("T-UNC-07", "Uncertainty", "HDI interval bounds", t07)

    def t08():
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            res = posterior_rate(trees, mat, rate="cpd", n_slices=30)
        assert (res["ess_proxy"] <= res["n_trees"]).all(), "ess_proxy should not exceed n_trees"
        return "ESS proxy verified"

    run_test("T-UNC-08", "Uncertainty", "ESS proxy bounds", t08)


# ========================================================================== #
# T-SPATIAL: Spatial tests
# ========================================================================== #
def test_spatial():
    def t01():
        bounds = np.array([[0, 0, 1, 1], [1, 0, 2, 1], [0, 1, 1, 2], [1, 1, 2, 2]], dtype=float)
        adj = adjacency_from_bounds(bounds, method="queen")
        assert adj[0, 0] == 1  # diagonal
        assert adj[0, 1] == 1  # edge contact
        assert adj[0, 3] == 1  # corner contact (queen)
        return f"queen adj:\n{adj}"

    run_test("T-SPATIAL-01", "Spatial", "adjacency_from_bounds queen", t01)

    def t02():
        bounds = np.array([[0, 0, 1, 1], [1, 0, 2, 1], [0, 1, 1, 2], [1, 1, 2, 2]], dtype=float)
        adj = adjacency_from_bounds(bounds, method="rook")
        assert adj[0, 3] == 0  # corner contact NOT counted in rook
        assert adj[0, 1] == 1  # edge contact IS counted
        return f"rook adj corner={adj[0, 3]}"

    run_test("T-SPATIAL-02", "Spatial", "adjacency_from_bounds rook", t02)

    def t03():
        x = np.array([0.0, 1.0, 2.0, 3.0])
        y = np.array([0.0, 0.0, 0.0, 0.0])
        adj = adjacency_from_coords(x, y, method="knn", k=2)
        assert adj[0, 0] == 1  # diagonal
        assert adj[0, 1] == 1  # nearest neighbour
        assert adj[0, 2] == 1  # second nearest
        # Symmetric
        assert np.array_equal(adj, adj.T)
        return f"knn adj symmetric: {np.array_equal(adj, adj.T)}"

    run_test("T-SPATIAL-03", "Spatial", "adjacency_from_coords knn", t03)

    def t04():
        x = np.array([0.0, 1.0, 3.0])
        y = np.array([0.0, 0.0, 0.0])
        adj = adjacency_from_coords(x, y, method="radius", r=1.5)
        assert adj[0, 1] == 1  # within radius
        assert adj[0, 2] == 0  # outside radius
        return "radius adj OK"

    run_test("T-SPATIAL-04", "Spatial", "adjacency_from_coords radius", t04)

    def t05():
        adj = np.array([[1, 1, 0], [1, 1, 1], [0, 1, 1]], dtype=np.int8)
        d = to_adjacency_dict(adj, site_ids=["a", "b", "c"])
        adj2 = from_adjacency_dict(d, site_ids=["a", "b", "c"])
        assert np.array_equal(adj, adj2)
        return "round-trip OK"

    run_test("T-SPATIAL-05", "Spatial", "to/from_adjacency_dict round-trip", t05)

    def t06():
        import matplotlib

        matplotlib.use("Agg")
        rates = pd.DataFrame({"CpD": [0.1, 0.2, 0.15, 0.3]}, index=["s1", "s2", "s3", "s4"])
        grid = pd.DataFrame(
            {"minx": [0, 1, 0, 1], "miny": [0, 0, 1, 1], "maxx": [1, 2, 1, 2], "maxy": [1, 1, 2, 2]}
        )
        ax = rate_map(rates, grid, rate="CpD")
        assert ax is not None
        return "rate_map returns Axes"

    run_test("T-SPATIAL-06", "Spatial", "rate_map generates plot", t06)


# ========================================================================== #
# T-COMPAT: Compatibility layer tests
# ========================================================================== #
def test_compat():
    tree = TreeArray.from_newick("((A:1,B:1):1,(C:1,D:1):1);")

    def t01():
        s1 = squeeze_root(tree, 1.0)
        s2 = slice_rootward(tree, 1.0)
        assert abs(s1.pd - s2.pd) < 1e-10
        return f"PD={s1.pd}"

    run_test("T-COMPAT-01", "Compat", "squeeze_root == slice_rootward", t01)

    def t02():
        s1 = squeeze_tips(tree, 1.0)
        s2 = slice_tipward(tree, 1.0)
        assert abs(s1.pd - s2.pd) < 1e-10
        return f"PD={s1.pd}"

    run_test("T-COMPAT-02", "Compat", "squeeze_tips == slice_tipward", t02)

    def t03():
        result = squeeze_int(tree, from_=1.5, to=0.5, invert=True)
        assert isinstance(result, list) and len(result) == 2
        # R order: [younger, older]
        return f"R-order: younger PD={result[0].pd}, older PD={result[1].pd}"

    run_test("T-COMPAT-03", "Compat", "squeeze_int invert R-order", t03)

    def t04():
        pieces, steps = phylo_pieces(tree, n=4, timeSteps=True)
        assert len(pieces) == 4
        assert len(steps) == 4
        # steps should be increasing (cumulative depth from root)
        assert all(steps[i] <= steps[i + 1] for i in range(len(steps) - 1))
        return f"steps={steps}"

    run_test("T-COMPAT-04", "Compat", "phylo_pieces timeSteps", t04)

    def t05():
        # Use a tree with varied terminal branch lengths
        tree_cat = TreeArray.from_newick("((((A:0.3,B:0.3):0.7,C:1.0):1.0,D:2.0):1.0,E:3.0);")
        kept1 = compat_prune(tree_cat, 0.5, method=1)  # keep tips with terminal >= 0.5
        kept2 = compat_prune(tree_cat, 0.5, method=2)  # drop tips with terminal >= 0.5
        assert kept1.n_tips >= 2
        assert kept2.n_tips >= 2
        return f"method=1: {kept1.n_tips} tips, method=2: {kept2.n_tips} tips"

    run_test("T-COMPAT-05", "Compat", "prune_tips method=1/2", t05)


# ========================================================================== #
# T-SIM: Simulation tests
# ========================================================================== #
def test_sim():
    def t01():
        tree = yule_tree(50, age=1.0, seed=42)
        assert tree.n_tips == 50
        assert tree.is_ultrametric
        return f"n_tips={tree.n_tips}, ultrametric={tree.is_ultrametric}"

    run_test("T-SIM-01", "Sim", "yule_tree generation", t01)

    def t02():
        tree = birth_death_tree(50, age=1.0, birth_rate=1.0, death_rate=0.2, seed=42)
        assert tree.n_tips == 50
        assert tree.is_ultrametric
        return f"n_tips={tree.n_tips}"

    run_test("T-SIM-02", "Sim", "birth_death_tree generation", t02)

    def t03():
        mat, coords = make_dataset(n_sites=20, n_species=15, structure="random", seed=42)
        assert mat.shape == (20, 15)
        return f"shape={mat.shape}"

    run_test("T-SIM-03", "Sim", "make_dataset random", t03)

    def t04():
        mat, coords = make_dataset(n_sites=20, n_species=15, structure="clustered", seed=42)
        assert mat.shape == (20, 15)
        return f"shape={mat.shape}"

    run_test("T-SIM-04", "Sim", "make_dataset clustered", t04)

    def t05():
        data = ps.datasets.sim_passerines(n_sites=20, n_species=20, n_trees=3, seed=42)
        assert "trees" in data
        assert "mat" in data
        assert "coords" in data
        assert "bounds" in data
        assert "adj" in data
        assert len(data["trees"]) == 3
        return f"trees={len(data['trees'])}, mat={data['mat'].shape}"

    run_test("T-SIM-05", "Sim", "sim_passerines dataset", t05)

    def t06():
        t1 = yule_tree(30, age=10.0, seed=42)
        t2 = yule_tree(30, age=10.0, seed=42)
        assert t1 == t2
        return "reproducibility verified"

    run_test("T-SIM-06", "Sim", "Seed reproducibility", t06)


# ========================================================================== #
# T-VIZ: Visualisation tests
# ========================================================================== #
def test_viz():
    import matplotlib

    matplotlib.use("Agg")

    tree = yule_tree(20, age=10.0, seed=42)
    mat, _ = make_dataset(n_sites=10, n_species=20, structure="clustered", seed=7)
    mat.columns = tree.tip_labels

    def t01():
        slice_pieces(tree, n=20)
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            tree2, mat2 = align_tree_matrix(tree, mat)
        prof = pd_per_slice(tree2, mat2, slice_pieces(tree2, n=20))
        ages = slice_pieces(tree2, n=20).ages
        fit = fit_rate(prof[0], ages)
        ax = ps.viz.plot_rate_line(prof[0], fit=fit, ages=ages)
        assert ax is not None
        return "plot_rate_line OK"

    run_test("T-VIZ-01", "Viz", "plot_rate_line", t01)

    def t02():
        sens = sensitivity(tree, mat, slice_grid=[10, 25, 50], rate="cpd")
        ax = ps.viz.plot_sensitivity(sens)
        assert ax is not None
        return "plot_sensitivity OK"

    run_test("T-VIZ-02", "Viz", "plot_sensitivity", t02)

    def t03():
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            post = posterior_rate([tree], mat, n_slices=20)
        ax = ps.viz.plot_posterior(post)
        assert ax is not None
        return "plot_posterior OK"

    run_test("T-VIZ-03", "Viz", "plot_posterior", t03)


# ========================================================================== #
# T-CLI: Command-line interface tests
# ========================================================================== #
def test_cli():
    """Drive the four subcommands through ``phyloslicer.cli.main.main``.

    Each case writes into a throwaway directory, so the repository stays clean;
    the exit code is what the shell sees, and argparse usage errors surface as
    ``SystemExit(2)``.
    """
    import tempfile
    from contextlib import redirect_stderr, redirect_stdout
    from io import StringIO

    from phyloslicer.cli.main import main

    tree = str(DATA_DIR / "medium_tree.tre")
    sites = str(DATA_DIR / "medium_mat.csv")
    ptrees = str(DATA_DIR / "posterior_trees")

    def _cli(argv):
        out, err = StringIO(), StringIO()
        with redirect_stdout(out), redirect_stderr(err):
            try:
                rc = main(argv)
            except SystemExit as exc:  # argparse usage errors
                rc = exc.code if isinstance(exc.code, int) else 2
        return rc, out.getvalue(), err.getvalue()

    def t01():
        with tempfile.TemporaryDirectory() as tmp:
            rc, _, err = _cli(["slice", tree, "--rootward", "5.0", "--out", f"{tmp}/out.tre"])
            assert rc == 0, f"rc={rc}: {err}"
            text = Path(f"{tmp}/out.tre").read_text(encoding="utf-8")
            assert ";" in text and len(text.strip()) > 0
            return f"Newick written ({len(text.strip())} chars)"

    run_test("T-CLI-01", "CLI", "slice --rootward writes Newick", t01)

    def t02():
        with tempfile.TemporaryDirectory() as tmp:
            rc, _, err = _cli(["slice", tree, "--tipward", "1.0", "--out", f"{tmp}/out.tre"])
            assert rc == 0, f"rc={rc}: {err}"
            assert Path(f"{tmp}/out.tre").exists()
            return "exit 0, Newick written"

    run_test("T-CLI-02", "CLI", "slice --tipward writes Newick", t02)

    def t03():
        with tempfile.TemporaryDirectory() as tmp:
            rc, _, err = _cli(["slice", tree, "--n-slices", "10", "--out", f"{tmp}/slices"])
            assert rc == 0, f"rc={rc}: {err}"
            files = sorted(Path(f"{tmp}/slices").glob("slice_*.tre"))
            assert len(files) == 10, [f.name for f in files]
            return f"{len(files)} slice files"

    run_test("T-CLI-03", "CLI", "slice --n-slices writes one file per slice", t03)

    def t04():
        with tempfile.TemporaryDirectory() as tmp:
            rc, _, err = _cli(
                [
                    "rates",
                    tree,
                    sites,
                    "--rate",
                    "cpd",
                    "--n-slices",
                    "30",
                    "--out",
                    f"{tmp}/rates.csv",
                ]
            )
            assert rc == 0, f"rc={rc}: {err}"
            cols = pd.read_csv(f"{tmp}/rates.csv").columns
            assert {"CpD", "PD", "pDO", "converged"} <= set(cols), list(cols)
            return f"columns: {', '.join(cols[:5])}"

    run_test("T-CLI-04", "CLI", "rates --rate cpd writes the CpD table", t04)

    def t05():
        with tempfile.TemporaryDirectory() as tmp:
            rc, _, err = _cli(
                [
                    "rates",
                    tree,
                    sites,
                    "--rate",
                    "cpe",
                    "--n-slices",
                    "30",
                    "--out",
                    f"{tmp}/rates.csv",
                ]
            )
            assert rc == 0, f"rc={rc}: {err}"
            cols = pd.read_csv(f"{tmp}/rates.csv").columns
            assert {"CpE", "PE", "pEO"} <= set(cols), list(cols)
            return f"columns: {', '.join(cols[:5])}"

    run_test("T-CLI-05", "CLI", "rates --rate cpe writes the CpE table", t05)

    def t06():
        import warnings

        with tempfile.TemporaryDirectory() as tmp:
            with warnings.catch_warnings():
                # the posterior draw has more tips than the matrix, and the
                # alignment says so loudly; that is expected, not a failure
                warnings.simplefilter("ignore")
                rc, _, err = _cli(
                    ["posterior", ptrees, sites, "--n-slices", "30", "--out", f"{tmp}/post.csv"]
                )
            assert rc == 0, f"rc={rc}: {err}"
            cols = pd.read_csv(f"{tmp}/post.csv").columns
            assert {"hdi_low", "hdi_high", "n_trees"} <= set(cols), list(cols)
            return f"columns: {', '.join(cols[:6])}"

    run_test("T-CLI-06", "CLI", "posterior writes the credible-interval table", t06)

    def t07():
        ref = REPO / "validation" / "reference"
        with tempfile.TemporaryDirectory() as tmp:
            rc, _, err = _cli(
                [
                    "validate",
                    str(ref / "bd20__tree.tre"),
                    str(ref / "bd20__random__mat.csv"),
                    "--reference",
                    str(ref / "bd20__random__CpD.csv"),
                    "--n-slices",
                    "50",
                    "--out",
                    f"{tmp}/v.csv",
                ]
            )
            assert rc == 0, f"rc={rc}: {err}"
            report = pd.read_csv(f"{tmp}/v.csv")
            assert len(report) > 0
            return f"{len(report)} sites validated"

    run_test("T-CLI-07", "CLI", "validate passes against a registered reference", t07)

    def t08():
        rc, _, err = _cli(["slice"])
        assert rc == 2, f"rc={rc}: {err}"
        assert "required" in err.lower() or "usage" in err.lower(), err
        return "exit 2 on a missing required argument"

    run_test("T-CLI-08", "CLI", "missing required argument exits 2", t08)

    def t09():
        with tempfile.TemporaryDirectory() as tmp:
            rc, _, err = _cli(
                ["slice", tree, "--rootward", "5.0", "--tipward", "3.0", "--out", f"{tmp}/o.tre"]
            )
            assert rc == 2, f"rc={rc}: {err}"
            assert "exactly one" in err, err
            return "exit 2 on mutually exclusive slice windows"

    run_test("T-CLI-09", "CLI", "conflicting --rootward/--tipward exits 2", t09)

    def t10():
        with tempfile.TemporaryDirectory() as tmp:
            log = f"{tmp}/run.json"
            rc, _, err = _cli(
                ["slice", tree, "--rootward", "5.0", "--out", f"{tmp}/o.tre", "--log", log]
            )
            assert rc == 0, f"rc={rc}: {err}"
            entry = json.loads(Path(log).read_text(encoding="utf-8"))
            assert {"version", "elapsed_s"} <= set(entry), list(entry)
            assert entry["version"] == ps.__version__, entry["version"]
            return f"log keys: {', '.join(sorted(entry))}"

    run_test("T-CLI-10", "CLI", "--log writes a JSON run summary", t10)


# ========================================================================== #
# T-PERF: Performance and benchmark tests
# ========================================================================== #
def test_perf():
    """The budgets the test plan states, measured on this machine.

    These are wall-clock budgets, so they are properties of the run, not of the
    algorithm; each one reports the elapsed time it observed.
    """
    import subprocess
    import tracemalloc

    ref = REPO / "validation" / "reference"
    large = REPO / "benchmarks" / "large"

    def t01():
        tree = TreeArray.from_newick(str(ref / "bd100__tree.tre"))
        mat = pd.read_csv(str(ref / "bd100__random__mat.csv"), index_col=0)
        t0 = time.perf_counter()
        res = ps.cpd_rate(tree, mat, n_slices=50)
        dt = time.perf_counter() - t0
        assert dt < 5.0, f"{dt:.2f}s >= 5s budget"
        assert res["converged"].any()
        return f"{len(mat)} sites x {tree.n_tips} tips in {dt:.2f}s"

    run_test("T-PERF-01", "Perf", "CpD on a 100-tip tree under 5s", t01)

    def t02():
        tree = TreeArray.from_newick(str(large / "large1000__tree.tre"))
        mat = pd.read_csv(str(large / "large1000__mat.csv"), index_col=0)
        t0 = time.perf_counter()
        res = ps.cpd_rate(tree, mat, n_slices=100)
        dt = time.perf_counter() - t0
        assert dt < 60.0, f"{dt:.2f}s >= 60s budget"
        assert len(res) == len(mat)
        return f"{len(mat)} sites x {tree.n_tips} tips in {dt:.2f}s"

    run_test("T-PERF-02", "Perf", "CpD on a 1000-tip tree under 60s", t02)

    def t03():
        # a 100-tip tree is under a millisecond to slice at any k, so the
        # measurement would be noise; use the largest bundled tree and repeat
        tree = TreeArray.from_newick(str(large / "large1000__tree.tre"))
        repeats = 5

        def median_millis(n_slices: int) -> float:
            times = []
            for _ in range(repeats):
                t0 = time.perf_counter()
                ps.slice_pieces(tree, n=n_slices).contribution_matrix()
                times.append(time.perf_counter() - t0)
            return sorted(times)[repeats // 2] * 1e3

        median_millis(10)  # warm-up: first call pays for import-time caches
        times = {n: median_millis(n) for n in (10, 50, 200)}
        assert times[10] <= times[50] <= times[200], times
        # cost per slice is constant, so time is linear in k up to the fixed
        # per-call overhead; the fitted exponent must sit near 1, not near 2
        exponent = math.log(times[200] / times[10]) / math.log(20.0)
        assert 0.3 <= exponent <= 1.3, f"exponent {exponent:.2f}, times {times}"
        return f"t(10)={times[10]:.2f}ms t(200)={times[200]:.2f}ms, exponent {exponent:.2f}"

    run_test("T-PERF-03", "Perf", "slice count scaling stays linear", t03)

    def t04():
        tree = TreeArray.from_newick(str(ref / "bd100__tree.tre"))
        mat = pd.read_csv(str(ref / "bd100__random__mat.csv"), index_col=0)
        peaks = []
        for _ in range(2):
            tracemalloc.start()
            ps.cpd_rate(tree, mat, n_slices=50)
            peaks.append(tracemalloc.get_traced_memory()[1])
            tracemalloc.stop()
        assert peaks[0] < 200 * 1024 * 1024, f"{peaks[0] / 1e6:.1f} MB peak"
        assert peaks[1] < 1.5 * peaks[0], f"peak grew {peaks[1] / max(peaks[0], 1):.2f}x"
        return f"peak {peaks[0] / 1e6:.1f} MB, second run {peaks[1] / 1e6:.1f} MB"

    run_test("T-PERF-04", "Perf", "memory stays bounded across repeats", t04)

    def t05():
        r = subprocess.run(
            [sys.executable, str(REPO / "benchmarks" / "recompute_ratios.py")],
            capture_output=True,
            text=True,
            timeout=300,
            env={**os.environ, "PYTHONPATH": str(REPO / "src")},
            cwd=str(REPO),
        )
        assert r.returncode == 0, r.stdout[-600:] + r.stderr[-600:]
        assert "quoted" in r.stdout
        return "documented speed-up ranges re-derived from the archived tables"

    run_test("T-PERF-05", "Perf", "benchmark tables reproduce the quoted ranges", t05)


# ========================================================================== #
# T-ERROR: Error and boundary tests
# ========================================================================== #
def test_error():
    def t01():
        try:
            TreeArray(tip_labels=["A"], edges=np.array([[1, 0]]), lengths=np.array([1.0]))
            return "ERROR: should raise"
        except ValueError:
            return "correctly raised"

    run_test("T-ERR-01", "Error", "1-tip tree raises", t01)

    def t02():
        try:
            TreeArray(
                tip_labels=["A", "B"],
                edges=np.array([[2, 0], [2, 1]]),
                lengths=np.array([np.nan, 1.0]),
            )
            return "ERROR: should raise"
        except ValueError:
            return "correctly raised"

    run_test("T-ERR-02", "Error", "NaN branch length raises", t02)

    def t03():
        try:
            TreeArray(
                tip_labels=["A", "B"],
                edges=np.array([[2, 0], [2, 1]]),
                lengths=np.array([-1.0, 1.0]),
            )
            return "ERROR: should raise"
        except ValueError:
            return "correctly raised"

    run_test("T-ERR-03", "Error", "Negative branch length raises", t03)

    def t04():
        try:
            TreeArray(
                tip_labels=["A", "A"],
                edges=np.array([[2, 0], [2, 1]]),
                lengths=np.array([1.0, 1.0]),
            )
            return "ERROR: should raise"
        except ValueError:
            return "correctly raised"

    run_test("T-ERR-04", "Error", "Duplicate tip labels raise", t04)

    def t05():
        # Create a cycle: A->B, B->A
        try:
            TreeArray(
                tip_labels=["A", "B"],
                edges=np.array([[2, 3], [3, 2]]),  # cycle between internal nodes
                lengths=np.array([1.0, 1.0]),
            )
            return "ERROR: should raise"
        except ValueError:
            return "correctly raised"

    run_test("T-ERR-05", "Error", "Cycle in tree raises", t05)

    def t06():
        try:
            TreeArray(
                tip_labels=["A", "B", "C"],
                edges=np.array([[3, 0], [3, 1], [5, 2]]),
                lengths=[1.0, 1.0, 1.0],
            )
            return "ERROR: should raise"
        except ValueError as exc:
            assert "unreachable" in str(exc), str(exc)
            return "correctly raised"

    run_test("T-ERR-06", "Error", "Disconnected component raises", t06)

    def t07():
        tree = TreeArray.from_newick("((A:1,B:1):1,(C:1,D:1):1);")
        mat = pd.DataFrame({"A": [1], "B": [1], "C": [1], "D": [1]}, index=["s1"])
        try:
            cpd_rate(tree, mat, n_slices=0)
            return "ERROR: should raise"
        except ValueError:
            return "correctly raised"

    run_test("T-ERR-07", "Error", "n_slices < 1 raises", t07)

    def t08():
        try:
            origin_time(0.5, percentile=1.5)
            return "ERROR: should raise"
        except ValueError:
            return "correctly raised"

    run_test("T-ERR-08", "Error", "percentile > 1 raises", t08)

    def t09():
        tree = TreeArray.from_newick("((A:1,B:1):1,(C:1,D:1):1);")
        try:
            slice_rootward(tree, 1.0, criterion="invalid")
            return "ERROR: should raise"
        except ValueError:
            return "correctly raised"

    run_test("T-ERR-09", "Error", "Invalid criterion raises", t09)

    def t10():
        tree = TreeArray.from_newick("((A:1,B:1):1,(C:1,D:1):1);")
        try:
            slice_pieces(tree, n=10, width=0.5)
            return "ERROR: should raise"
        except ValueError:
            return "correctly raised"

    run_test("T-ERR-10", "Error", "Both n and width raises", t10)


# ========================================================================== #
# T-E2E: End-to-end workflow tests
# ========================================================================== #
def test_e2e():
    def t01():
        """Full CpD workflow via API."""
        tree = TreeArray.from_newick(str(DATA_DIR / "medium_tree.tre"))
        mat = pd.read_csv(str(DATA_DIR / "medium_mat.csv"), index_col=0)
        mat = (mat > 0).astype(float)
        res = cpd_rate(tree, mat, n_slices=50)
        res.to_csv(RESULTS_DIR / "e2e_cpd.csv", index=False)
        assert len(res) == len(mat)
        n_conv = int(res["converged"].sum())
        assert n_conv > 0, "at least some sites should converge"
        return f"{len(res)} sites, {n_conv} converged"

    run_test("T-E2E-01", "E2E", "Full CpD workflow (API)", t01)

    def t02():
        """Full CpE workflow via API."""
        tree = TreeArray.from_newick(str(DATA_DIR / "medium_tree.tre"))
        mat = pd.read_csv(str(DATA_DIR / "medium_mat.csv"), index_col=0)
        mat = (mat > 0).astype(float)
        res = cpe_rate(tree, mat, n_slices=50)
        res.to_csv(RESULTS_DIR / "e2e_cpe.csv", index=False)
        assert "CpE" in res.columns
        return f"{len(res)} sites"

    run_test("T-E2E-02", "E2E", "Full CpE workflow (API)", t02)

    def t03():
        """Full CpB workflow via API."""
        tree = TreeArray.from_newick(str(DATA_DIR / "medium_tree.tre"))
        mat = pd.read_csv(str(DATA_DIR / "medium_mat.csv"), index_col=0)
        mat = (mat > 0).astype(float)
        bounds = pd.read_csv(str(DATA_DIR / "grid_bounds.csv"))
        adj = adjacency_from_bounds(bounds.to_numpy(), method="queen")
        # Truncate to match matrix
        n = min(len(mat), adj.shape[0])
        adj = adj[:n, :n]
        mat = mat.iloc[:n]
        res = cpb_rate(tree, mat, adj, n_slices=50, component="sorensen")
        res.to_csv(RESULTS_DIR / "e2e_cpb.csv", index=False)
        assert "CpB" in res.columns
        return f"{len(res)} sites"

    run_test("T-E2E-03", "E2E", "Full CpB workflow (API)", t03)

    def t04():
        """Full posterior analysis workflow."""
        pdir = str(DATA_DIR / "posterior_trees")
        mat = pd.read_csv(str(DATA_DIR / "medium_mat.csv"), index_col=0)
        mat = (mat > 0).astype(float)
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            res = posterior_rate(pdir, mat, rate="cpd", n_slices=30, hdi=0.95)
        res.to_csv(RESULTS_DIR / "e2e_posterior.csv", index=False)
        assert "hdi_low" in res.columns
        return f"{len(res)} sites, n_trees={res['n_trees'].iloc[0]}"

    run_test("T-E2E-04", "E2E", "Full posterior workflow (API)", t04)

    def t05():
        """Full CLI workflow."""
        import subprocess

        env = os.environ.copy()
        env["PYTHONPATH"] = str(REPO / "src")

        # Clean up any previous output
        for f in ["cli_slice.tre", "cli_rates.csv"]:
            p = RESULTS_DIR / f
            if p.exists():
                p.unlink()

        # slice (output already cleaned up)
        r = subprocess.run(
            [
                sys.executable,
                "-m",
                "phyloslicer.cli.main",
                "slice",
                str(DATA_DIR / "medium_tree.tre"),
                "--rootward",
                "5.0",
                "--out",
                str(RESULTS_DIR / "cli_slice.tre"),
            ],
            capture_output=True,
            text=True,
            timeout=60,
            env=env,
            cwd=str(REPO),
        )
        assert r.returncode == 0, f"slice failed: {r.stderr}"
        assert (RESULTS_DIR / "cli_slice.tre").exists()

        # rates (no --force argument for this subcommand)
        rates_out = RESULTS_DIR / "cli_rates.csv"
        if rates_out.exists():
            rates_out.unlink()
        r = subprocess.run(
            [
                sys.executable,
                "-m",
                "phyloslicer.cli.main",
                "rates",
                str(DATA_DIR / "medium_tree.tre"),
                str(DATA_DIR / "medium_mat.csv"),
                "--rate",
                "cpd",
                "--n-slices",
                "50",
                "--out",
                str(rates_out),
            ],
            capture_output=True,
            text=True,
            timeout=120,
            env=env,
            cwd=str(REPO),
        )
        assert r.returncode == 0, f"rates failed: {r.stderr}"
        assert rates_out.exists()

        return "slice + rates CLI OK"

    run_test("T-E2E-05", "E2E", "Full CLI workflow", t05)

    def t06():
        """Cross-validation against reference data."""
        import subprocess

        env = os.environ.copy()
        env["PYTHONPATH"] = str(REPO / "src")

        ref_dir = REPO / "validation" / "reference"
        ref_tree = str(ref_dir / "bd20__tree.tre")
        ref_mat = str(ref_dir / "bd20__random__mat.csv")
        ref_csv = str(ref_dir / "bd20__random__CpD.csv")
        out_csv = str(RESULTS_DIR / "e2e_validate.csv")

        r = subprocess.run(
            [
                sys.executable,
                "-m",
                "phyloslicer.cli.main",
                "validate",
                ref_tree,
                ref_mat,
                "--reference",
                ref_csv,
                "--n-slices",
                "50",
                "--out",
                out_csv,
            ],
            capture_output=True,
            text=True,
            timeout=120,
            env=env,
            cwd=str(REPO),
        )
        # validate may return 0 (all match) or 1 (some disagree, but that's OK for our test)
        # The key is that it ran and produced output
        assert (RESULTS_DIR / "e2e_validate.csv").exists(), f"no output: {r.stderr}"
        report = pd.read_csv(out_csv)
        eq_rate = report["equivalent"].mean()
        return f"equivalence rate: {eq_rate:.4f}"

    run_test("T-E2E-06", "E2E", "Cross-validation (validate)", t06)

    def t07():
        """Visualization full workflow."""
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        tree = TreeArray.from_newick(str(DATA_DIR / "medium_tree.tre"))
        mat = pd.read_csv(str(DATA_DIR / "medium_mat.csv"), index_col=0)
        mat = (mat > 0).astype(float)
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            tree2, mat2 = align_tree_matrix(tree, mat)
            stack = slice_pieces(tree2, n=50)
            prof = pd_per_slice(tree2, mat2, stack)
            fit = fit_rate(prof[0], stack.ages)
            ax = ps.viz.plot_rate_line(prof[0], fit=fit, ages=stack.ages)
            ax.figure.savefig(str(RESULTS_DIR / "e2e_rate_line.png"), dpi=100, bbox_inches="tight")
            plt.close("all")

        return "figures saved"

    run_test("T-E2E-07", "E2E", "Visualization workflow", t07)


# ========================================================================== #
# Main runner
# ========================================================================== #
def main():
    print("=" * 70)
    print("PhyloSlicer Comprehensive Test Suite")
    print("=" * 70)
    print(f"Data dir:    {DATA_DIR}")
    print(f"Results dir: {RESULTS_DIR}")
    print(f"Python:      {sys.executable}")
    print(f"Version:     {ps.__version__}")
    print()

    t0 = time.perf_counter()

    print("--- T-INSTALL: Installation & Dependencies ---")
    test_install()

    print("\n--- T-IO: Input/Output ---")
    test_io()

    print("\n--- T-CORE: Core Algorithms ---")
    test_core()

    print("\n--- T-INDICES: Diversity Indices ---")
    test_indices()

    print("\n--- T-RATES: Cumulative Rates ---")
    test_rates()

    print("\n--- T-SLICING: Slicing ---")
    test_slicing()

    print("\n--- T-UNC: Uncertainty ---")
    test_uncertainty()

    print("\n--- T-SPATIAL: Spatial ---")
    test_spatial()

    print("\n--- T-COMPAT: Compatibility Layer ---")
    test_compat()

    print("\n--- T-SIM: Simulation ---")
    test_sim()

    print("\n--- T-VIZ: Visualisation ---")
    test_viz()

    print("\n--- T-CLI: Command-Line Interface ---")
    test_cli()

    print("\n--- T-ERROR: Error & Boundary ---")
    test_error()

    print("\n--- T-E2E: End-to-End ---")
    test_e2e()

    print("\n--- T-PERF: Performance & Benchmarks ---")
    test_perf()

    elapsed = time.perf_counter() - t0

    # Summary
    print("\n" + "=" * 70)
    print("SUMMARY")
    print("=" * 70)
    n_pass = sum(1 for r in results if r.passed)
    n_fail = sum(1 for r in results if not r.passed)
    n_total = len(results)
    print(
        f"Total: {n_total} | Passed: {n_pass} | Failed: {n_fail}"
        f" | Pass rate: {n_pass / n_total * 100:.1f}%"
    )
    print(f"Total elapsed: {elapsed:.1f}s")

    # Category breakdown
    cats = {}
    for r in results:
        if r.category not in cats:
            cats[r.category] = {"pass": 0, "fail": 0}
        if r.passed:
            cats[r.category]["pass"] += 1
        else:
            cats[r.category]["fail"] += 1
    print("\nBy category:")
    for cat, counts in sorted(cats.items()):
        total = counts["pass"] + counts["fail"]
        print(f"  {cat:15s}: {counts['pass']}/{total} passed")

    if n_fail:
        print("\nFailed tests:")
        for r in results:
            if not r.passed:
                print(f"  {r.test_id}: {r.description}")
                print(f"    Error: {r.error}")

    # Save results as JSON
    report = {
        "version": ps.__version__,
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "total": n_total,
        "passed": n_pass,
        "failed": n_fail,
        "pass_rate": n_pass / n_total,
        "elapsed_s": elapsed,
        "results": [
            {
                "test_id": r.test_id,
                "category": r.category,
                "description": r.description,
                "passed": r.passed,
                "elapsed_s": r.elapsed_s,
                "error": r.error,
            }
            for r in results
        ],
    }
    report_path = LOGS_DIR / "test_results.json"
    with open(report_path, "w") as f:
        json.dump(report, f, indent=2)
    print(f"\nDetailed results: {report_path}")

    return 0 if n_fail == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
